Configuration file usage added, on-screen logs verbosity increased, bug fixes.

diff --git a/src/vnc-picker b/src/vnc-picker
--- a/src/vnc-picker
+++ b/src/vnc-picker
@@ -36,17 +36,18 @@
 #
 
 shopt -s extglob
-PS4="CMD:${0}:${LINENO}: "
+PS4="CMD:\${0}:\${LINENO}: "
+
+declare -r thisDir="$( dirname "${0}" )"
+declare -r nodesConfPrinter="${thisDir}/print-nodes-confs.py"
 
 # #
  #
 #
 
+
 declare -ri vncNodesParamItemsQuantity="10"
-declare -ra vncNodes=(\
-"user-name" "host-name" "22" "localhost" "12345" "5901" ":1" "800x600" "86" "${HOME}/.vnc/passwd.hostname"
-"user-name" "host-name" "22" "localhost" "12345" "5901" ":1" "800x600" "86" "${HOME}/.vnc/passwd.hostname"
-)
+declare -a  vncNodes
 
 # Objects used to store in _array_ information sufficient to acces VNC node.
 declare -a  sshNameLst=""
@@ -235,31 +236,37 @@ function createTempFile {
     return ${codeSuccess}
 }
 
-#function createPipeFile {
-    #local filePipe=""
-
-    #filePipe="/tmp/$( getNextUniqueName )"
-    #mkfifo --mode=600 "${filePipe}"
-    #trap 'rm -f "${filePipe}"' EXIT
-    #[ ! -p "${filePipe}" ] \
-        #&& echo "ERROR:${0}:${LINENO}: failed to create fifo file." >&2 \
-        #&& exit ${errorMisc}
-    #echo -n "${filePipe}"
-#}
-
-#function getNextUniqueName {
-    #local fileName=""
-
-    #while : ; do
-        #((uniqueNameStartValue++))
-        #fileName="$$_$uniqueNameStartValue"
-        #[ ! -e "${fileName}" ] \
-            #&& echo "fileName" \
-            #&& return ${codeSuccess}
-    #done
-#}
-
 function loadVNCNodesList {
+    loadFromConfFileVNCNodesList
+    splitVNCNodesListIntoOtherArrays
+}
+
+function loadFromConfFileVNCNodesList {
+    local idx=""
+
+    set -e # This will react on error exit codes from '${nodesConfPrinter}'
+    idx=0
+    while read singleStr ; do
+        case "${singleStr}" in
+            '[node description start]')
+                true
+                ;;
+            '[node description stop]')
+                true
+                ;;
+            *)
+                if [ -z "${singleStr}" ] ; then
+                    echo "ERROR:${0}:${LINENO}: Got empty string from configuration file." >&2
+                    exit ${errorMisc}
+                fi
+                vncNodes[idx]="${singleStr}"
+                idx=$((idx + 1))
+        esac
+    done <<< "$( "${nodesConfPrinter}" )"
+    set +e
+}
+
+function splitVNCNodesListIntoOtherArrays {
     local idx=""
 
     vncNodesQuantity=0
@@ -279,7 +286,6 @@ function loadVNCNodesList {
         ((vncNodesQuantity++))
 
     done
-
 }
 
 function getBusyScreenIds {
@@ -322,7 +328,7 @@ function getFreeScreenId {
     screenFreeId=":$(( screenLastBusyNumericId + 1 ))"
     echo "${screenFreeId}"
 
-    # Need here error check: was it really found and composed a valid screen identifier.
+    # XXX - Need here error check: was it really found and composed a valid screen identifier.
     #return ${codeFailure}
     #return ${codeSuccess}
 }
@@ -364,13 +370,13 @@ function printAllListOfRemoteScreensId {
 
     while read processOwner processId command remoteSessionScreenId misc ; do
         echo "${remoteSessionScreenId}"
-    done <<< "$( ssh -p "${sshPortNumber}" "${sshIdWithHost}" \
+    done <<< "$( set -x ; ssh -p "${sshPortNumber}" "${sshIdWithHost}" \
                 "ps ax -o user,pid,command \
                     |  grep    \"^${targetUserId}\" \
                     | egrep    \"${exprWantedVncExe}\" \
                     | egrep -v \"${exprExcludeNonVncExe}\" \
                     | egrep    \"${targetRfbPortNumberExpression}\" \
-                    |  grep -v grep " )"
+                    |  grep -v grep " ; set +x)"
 }
 
 function isAccountNumberIsInRange {
@@ -453,9 +459,11 @@ function wakeTunnelUp {
     command="ssh -N -L ${localTunPortNumberLst[tgtX]}:${tunHostLst[tgtX]}:${vncHostPortNumberLst[tgtX]} -p ${sshPortNumberLst[tgtX]} ${accountId}"
 
     if ! isCommandRunning "${command}" ; then
+        set -x
         ${command} &
         [ ${?} == 0 ] \
-            && return ${codeSuccess}
+            && set +x && return ${codeSuccess}
+        set +x
     else
         echo "INFO:${0}:${LINENO}: It seems tunnel is already opened. Do nothing."
         return ${codeSuccess}
@@ -475,6 +483,8 @@ function wakeVNCServerUp {
 
     screenFreeId="$( getFreeScreenId "${sshPortNumberLst[tgtX]}" "${accountIdWithHost}" )"
 
+    set -x
+
     ##
     # Here may be possible bug with VNC client-server relations. Ubuntu
     # 'xvncviewer' (TightVNC on-board) and Fedora 'vncserver'
@@ -488,6 +498,7 @@ function wakeVNCServerUp {
     # Will explicitly substitude X-Display identifier from settings and configuration data with obtained free identifier.
     if ( ! ssh -p "${sshPortNumberLst[tgtX]}" "${accountIdWithHost}" "${vncServerExecutable} ${screenFreeId} -dpi ${screenDpi[tgtX]} -geometry ${screenSzLst[tgtX]} -nevershared -localhost -rfbport ${vncHostPortNumberLst[tgtX]} -nolisten tcp ${screenFreeId}" )
     then
+        set +x
         # XXX - sshNameLst[tgtX] must be evaluated at run time???
         remoteProcessListEntry="$( printSingleRemoteScreenId "${sshPortNumberLst[tgtX]}" \
                                   "${accountIdWithHost}" \
@@ -501,8 +512,11 @@ function wakeVNCServerUp {
             return ${codeSuccess}
         fi
     else
+        set +x
         return ${codeSuccess}
     fi
+
+    set +x
     return ${codeFailure}
 }
 
@@ -511,8 +525,6 @@ function vncStart {
     local -r tgtX=$(( ${1} - 1 ))
 
     local accountId="${sshNameLst[tgtX]}@${vncHostLst[tgtX]}"
-
-    set -x
 
     # XXX - SSH tunnel needs some time to restore connection. It may be tested on the fly, or it may have several connection attempts. The last seems more safe, it Netfilter have 'limit' rules on SSH's service port.
     for attemptNumber in 1 2 3 ; do
@@ -532,8 +544,6 @@ function vncConnect {
 
     local feedbackVncViewer=${codeFailure}
 
-    set -x
-
     if ! isTunnelExist "$(( tgtX + 1 ))" ; then
         ! wakeTunnelUp "$(( tgtX + 1 ))" \
             && echo "ERROR:${0}:${LINENO}: Failed to detect or wakeup SSH tunnel to node '${sshNameLst[tgtX]}@${vncHostLst[tgtX]}'." >&2 \
@@ -546,8 +556,10 @@ function vncConnect {
     # XXX - SSH tunnel needs some time to restore connection. It may be tested on the fly, or it may have several connection attempts. The last seems more safe, it Netfilter have 'limit' rules on SSH's service port.
     for attemptNum in 1 2 ; do
         echo "INFORMATION:${0}:${LINENO}: Going to connect with: '${vncViewConnectCommand}'. Try number '${attemptNum}'." >&2
+        set -x
         ${vncViewConnectCommand} \
-            && return ${codeSuccess}
+            && set +x && return ${codeSuccess}
+        set +x
         echo "ERROR:${0}:${LINENO}: VNC-Viewer launch try number '${attemptNum}' failed." >&2
         sleep 3
     done
@@ -568,9 +580,11 @@ function vncStop {
 
     if ( ! ssh -p "${sshPortNumberLst[tgtX]}" "${sshNameLst[tgtX]}@${vncHostLst[tgtX]}" "${vncServerExecutable} -kill ${remoteSessionScreenId}" )
     then
+        set +x
         echo "ERROR:${0}:${LINENO}: Failed with server process shutdown on '${tunHostLst[tgtX]}:${localTunPortNumberLst[tgtX]}'. Check if X-Display identifier '${remoteSessionScreenId}' was detected properly inside this script." >&2
         return ${codeFailure}
     else
+        set +x
         return ${codeSuccess}
     fi
 }
@@ -585,15 +599,17 @@ function sshTunnelShutdown {
     local     pid=""
     local -r  command="ssh -N -L ${localTunPortNumberLst[index]}:localhost:${vncHostPortNumberLst[index]} -p ${sshPortNumberLst[index]} ${sshNameLst[index]}@${vncHostLst[index]}"
 
-    set -x
-
     while : ; do
+        set -x
+
         pid="$( isCommandRunning "${command}" )"
 
         if [ -n "${pid}" ] ; then
             kill -9 ${pid} 2>/dev/null >/dev/null \
                 ; feedback=${?}
         fi
+
+        set +x
 
         [ "${feedback}" != 0 ] \
             && echo "ERROR:${0}:${LINENO}: Failed to stop tunnel instance with PId='${pid}'. Is it already down?" >&2 \
@@ -781,11 +797,17 @@ This is free software: you are free to change and redistribute it. There is NO W
 "
 }
 
+
+
+
+  #
+ # #
 # # #
  # #
-# #
- #
-#
+  #
+
+
+
 
 [ ${#} == 0 ] \
     && showDoc \
@@ -849,8 +871,10 @@ case "${routineName}" in
             selectedActions="$( splitListToStringsWithActionsNames "${selectedActions}" )"
 
             processAllSelectedNodes "${selectedActions}" "${selectedNodesNumbersList[@]}"
-            echo ""
-            read -p "    Press 'Enter' to proceed..."
+            echo -ne "\n\n"
+            echo -n  "    Press 'Enter' to proceed..."
+            echo -ne "\n\n"
+            read -p  ""
         done
     done
     rm -f "${fileWithDialogFeedback}"
@@ -886,10 +910,17 @@ esac
 read -p "    Job done. Press 'Enter' to exit..."
 exit ${errorState}
 
+
+
+
+  #
+ # #
 # # #
  # #
-# #
- #
+  #
+
+
+
 
 # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # #
 
